server:
    port: 8083
    servlet:
      context-path: /springData
spring:
  application:
    name: spring-data-demo


  datasource:
    url: jdbc:mysql://localhost:3306/userdb?useSSL=false
    username: root
    password: medhy@abhi
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:    hibernate:      ddl-auto: update