server:  port: 8091
feign:
  client:
    config:
      default:
        readTimeout: 1500
        connectTimeout: 500


service:
    base:
        url: http://localhost:8083/springData/
    name: feignUserService