server:
  port: 8090

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/devtechsolution/cloud-config-props
        health: 
          enabled: true
                    
      label: master
      name: config-server
      
management:
  endpoint:
    health:
      show-details: always 
     
      
      
          
        
       
