server:
  port: 8090

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/devtechsolution/cloud-config-props
      label: main
      name: config-server
      
      
          
        
       
